# Use this aggregated ClusterRole to grant to
# Scoby Hook for Triggermesh premissions on
# registered objects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # There might be an addressable-resolver ClusterRole if Knative Eventing is installed.
  # This would be a duplicate for TriggerMesh's scoby that would add support for scenarios
  # where Knative Eventing is not installed but Knative Serving is.
  name: scoby-hook-triggermesh
  labels:
    eventing.knative.dev/release: devel
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: scoby-hook-triggermesh
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      scoby.triggermesh.io/scoby-hook-triggermesh: "true"
rules: [] # Rules are automatically filled in by the controller manager.

