kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scoby-hook-triggermesh
  labels:
    scoby.triggermesh.io/crdregistration: "true"
    app.kubernetes.io/name: scoby
rules:
- apiGroups:
  - "extensions.triggermesh.io"
  resources:
  - kuards
  verbs:
  - get
  - list
  - watch

---

# ClusterRole that will be aggregated at Scoby so that it can
# manage these objects.

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crd-registrations-scoby-kuard
  labels:
    scoby.triggermesh.io/crdregistration: "true"
    app.kubernetes.io/name: scoby
# Do not use this role directly. These rules will be added to the "crd-registrations-scoby" role.
rules:
- apiGroups:
  - "extensions.triggermesh.io"
  resources:
  - kuards
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - "extensions.triggermesh.io"
  resources:
  - kuards/status
  verbs:
  - get
  - update
  - patch
  # If a hook is used for finalization, the finalize resource
  # must be added to the ClusterRole.
- apiGroups:
  - "extensions.triggermesh.io"
  resources:
  - kuards/finalizers
  verbs:
  - list
  - watch
  - create
  - update
  - delete
