
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scoby-hook-awss3sources
  labels:
    # Do not use this role directly.
    # These rules will be added to the "scoby-hook-triggermesh" role.
    scoby.triggermesh.io/scoby-hook-triggermesh: "true"
    app.kubernetes.io/name: scoby-hook-triggermesh
rules:
- apiGroups:
  - sources.triggermesh.io
  resources:
  - awss3sources
  verbs:
  - get

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scoby-awss3sources
  labels:
    # Do not use this role directly. These rules will be added to the "crd-registrations-scoby" role.
    scoby.triggermesh.io/crdregistration: "true"
    app.kubernetes.io/name: scoby
rules:
- apiGroups:
  - sources.triggermesh.io
  resources:
  - awss3sources
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - sources.triggermesh.io
  resources:
  - awss3sources/status
  verbs:
  - get
  - update
  - patch
  # If a hook is used for finalization, the finalize resource
  # must be added to the ClusterRole.
- apiGroups:
  - sources.triggermesh.io
  resources:
  - awss3sources/finalizers
  verbs:
  - update
