apiVersion: scoby.triggermesh.io/v1alpha1
kind: CRDRegistration
metadata:
  name: awss3sources
spec:
  crd: awss3sources.sources.triggermesh.io
  hook:
    address:
      uri: "http://:8080/v1"
      ref:
        apiVersion: v1
        kind: Service
        name: scoby-hook-triggermesh
        namespace: triggermesh

    initialization:
      enabled: true
      apiVersion: "1"
    finalization:
      enabled: true
      apiVersion: "1"

  workload:
    formFactor:
      deployment:
        replicas: 1
    fromImage:
      repo: gcr.io/triggermesh/awssqssource-adapter:v1.24.3

    statusConfiguration:
      conditionsFromHook:
      - type: Subscribed